import LinkageCompleteIntersectionsDeterminantalIdealsFoundationCanonicalLaneLean.AdmissibleClass
import LinkageCompleteIntersectionsDeterminantalIdealsFoundationCanonicalLaneLean.BridgeLemmas
import LinkageCompleteIntersectionsDeterminantalIdealsFoundationCanonicalLaneLean.GateLemmas
import LinkageCompleteIntersectionsDeterminantalIdealsFoundationCanonicalLaneLean.LinkagePackage
import LinkageCompleteIntersectionsDeterminantalIdealsFoundationCanonicalLaneLean.CompleteIntersectionPackage
import LinkageCompleteIntersectionsDeterminantalIdealsFoundationCanonicalLaneLean.DeterminantalIdealsPackage
import LinkageCompleteIntersectionsDeterminantalIdealsFoundationCanonicalLaneLean.FinalTheorem

namespace HautevilleHouse
namespace LinkageCompleteIntersectionsDeterminantalIdealsFoundationCanonicalLaneLean

-- Root module for the package

end LinkageCompleteIntersectionsDeterminantalIdealsFoundationCanonicalLaneLean
end HautevilleHouse